apiVersion: apps/v1
kind: Deployment
metadata:
  name: t24-data-validator-deployment
spec:
  selector:
    matchLabels:
      app: t24-data-validator-app
  replicas: 1
  template:
    metadata:
      labels:
        app: t24-data-validator-app
    spec:
      containers:
        - name: t24-data-validator-app
          image: t24-data-validator-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: t24-data-validator-secret
                  key: server.port
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: t24-data-validator-secret
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: t24-data-validator-secret
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: t24-data-validator-secret
                  key: spring.datasource.password
                     
---                 
apiVersion: v1
kind: Service
metadata:
  name: t24-data-validator-service
spec:
  type: NodePort
  selector:
    app: t24-data-validator-app
  
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8081
      nodePort: 31112


