logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: t24-data-validator-service

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    
management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health

        
        