spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - namespace: default
            name: t24-data-validator-config
      reload:
        enabled: true
        mode: event
        strategy: polling
